DROP TABLE IF EXISTS SUBMETE;
DROP TABLE IF EXISTS RESPOSTA;
DROP TABLE IF EXISTS AVALIACAO_QUESTAO;
DROP TABLE IF EXISTS QUESTAO;

-- Tabela de Questões (sem ID_AVALIACAO)
CREATE TABLE QUESTAO (
	ID_QUESTAO INT NOT NULL,
	ENUNCIADO TEXT NOT NULL,
	TIPO VARCHAR(100),
	VALOR_PONTO NUMERIC(5,1) NOT NULL CHECK (VALOR_PONTO >= 0),
	RESPOSTA_CORRETA TEXT,
	-- ID_AVALIACAO REMOVIDO
	CONSTRAINT "PK_QUESTAO" PRIMARY KEY(ID_QUESTAO)
);

-- Tabela Avaliacao_Questao (PK AJUSTADA)
CREATE TABLE Avaliacao_Questao (
    ID_AVALIACAO INT NOT NULL,
    ID_QUESTAO INT NOT NULL,
    ID_PROFESSOR INT, -- Professor que elaborou/adicionou a questão na avaliação
    valor_total NUMERIC(5, 1) CHECK (valor_total >= 0),
    PRIMARY KEY (ID_AVALIACAO, ID_QUESTAO), -- Chave primária ajustada
    FOREIGN KEY (ID_AVALIACAO) REFERENCES Avaliacao(ID_AVALIACAO) ON DELETE CASCADE,
    FOREIGN KEY (ID_QUESTAO) REFERENCES Questao(ID_QUESTAO) ON DELETE CASCADE,
    FOREIGN KEY (ID_PROFESSOR) REFERENCES Professor(ID_PROFESSOR) ON DELETE SET NULL
);

-- Tabela de Submissão de Respostas (NOVA - Substitui RESPOSTA e SUBMETE)
CREATE TABLE RESPOSTA_ALUNO (
    NUM_MATRICULA INT NOT NULL,
    ID_AVALIACAO INT NOT NULL,
    ID_QUESTAO INT NOT NULL,
    TEXTO_RESPOSTA TEXT,
    NOTA_OBTIDA NUMERIC(5, 1) CHECK (NOTA_OBTIDA >= 0),
    
    -- A Chave Primária é a combinação das três, garantindo que um aluno
    -- só pode responder uma vez a cada questão de cada avaliação.
    CONSTRAINT "PK_RESPOSTA_ALUNO" PRIMARY KEY (NUM_MATRICULA, ID_AVALIACAO, ID_QUESTAO),
    
    -- Chaves Estrangeiras
    CONSTRAINT "FK_RESPOSTA_ALUNO_ALUNO" FOREIGN KEY (NUM_MATRICULA)
        REFERENCES ALUNO(NUM_MATRICULA) ON DELETE CASCADE,
    
    -- Esta FK aponta para a tabela de junção, garantindo que
    -- a resposta só é válida para uma questão que REALMENTE existe nessa avaliação.
    CONSTRAINT "FK_RESPOSTA_ALUNO_AVALIACAO_QUESTAO" FOREIGN KEY (ID_AVALIACAO, ID_QUESTAO)
        REFERENCES Avaliacao_Questao(ID_AVALIACAO, ID_QUESTAO) ON DELETE CASCADE
);

