CREATE DATABASE sistema_academico;

-- Database: sistema_academico
-- DROP DATABASE IF EXISTS sistema_academico;
-- CREATE DATABASE sistema_academico;


-- Tabela de Usuários
CREATE TABLE USUARIO (
    ID_USUARIO INT NOT NULL,
    TIPO VARCHAR(50) NOT NULL CHECK (TIPO IN ('aluno', 'professor', 'admin')),
    SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CONSTRAINT "PK_USUARIO" PRIMARY KEY (ID_USUARIO),
    CONSTRAINT "UQ_USUARIO" UNIQUE (ID_USUARIO)
);


-- Tabela de Alunos
CREATE TABLE ALUNO (
    NUM_MATRICULA INT NOT NULL,
    CURSO VARCHAR(255),
    ID_ALUNO INT NOT NULL,
    CONSTRAINT "PK_ALUNO" PRIMARY KEY (NUM_MATRICULA),
    CONSTRAINT "UQ_ALUNO_USUARIO" UNIQUE (ID_ALUNO),
    CONSTRAINT "FK_ALUNO_USUARIO" FOREIGN KEY (ID_ALUNO)
        REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);


-- Tabela de Professores
CREATE TABLE PROFESSOR (
    ID_PROFESSOR INT NOT NULL,
    DEPARTAMENTO VARCHAR(255),
    CONSTRAINT "PK_PROFESSOR" PRIMARY KEY (ID_PROFESSOR),
    CONSTRAINT "UQ_PROFESSOR_USUARIO" UNIQUE (ID_PROFESSOR),
    CONSTRAINT "FK_PROFESSOR_USUARIO" FOREIGN KEY (ID_PROFESSOR)
        REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);


-- Tabela de Disciplinas
CREATE TABLE DISCIPLINA (
    ID_DISCIPLINA INT NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    COD_DISCIPLINA VARCHAR(50) NOT NULL,
    ID_PROFESSOR INT,
    CONSTRAINT "PK_DISCIPLINA" PRIMARY KEY (ID_DISCIPLINA),
    CONSTRAINT "UQ_DISCIPLINA_CODIGO" UNIQUE (COD_DISCIPLINA),
    CONSTRAINT "FK_DISCIPLINA_PROFESSOR" FOREIGN KEY (ID_PROFESSOR)
        REFERENCES PROFESSOR(ID_PROFESSOR) ON DELETE SET NULL ON UPDATE CASCADE
);


-- Tabela de Avaliações
CREATE TABLE AVALIACAO (
    ID_AVALIACAO INT NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    DATA_FIM DATE,
    ID_PROFESSOR INT,
    ID_DISCIPLINA INT NOT NULL,
    CONSTRAINT "PK_AVALIACAO" PRIMARY KEY (ID_AVALIACAO),
    CONSTRAINT "FK_AVALIACAO_PROFESSOR" FOREIGN KEY (ID_PROFESSOR)
        REFERENCES PROFESSOR(ID_PROFESSOR) ON DELETE SET NULL,
    CONSTRAINT "FK_AVALIACAO_DISCIPLINA" FOREIGN KEY (ID_DISCIPLINA)
        REFERENCES DISCIPLINA(ID_DISCIPLINA) ON DELETE CASCADE
);


-- Tabela de Questões
CREATE TABLE QUESTAO (
    ID_QUESTAO INT NOT NULL,
    ENUNCIADO TEXT NOT NULL,
    TIPO VARCHAR(100),
    VALOR_PONTO NUMERIC(5, 2) NOT NULL CHECK (VALOR_PONTO >= 0),
    RESPOSTA_CORRETA TEXT,
    ID_AVALIACAO INT NOT NULL,
    CONSTRAINT "PK_QUESTAO" PRIMARY KEY (ID_QUESTAO),
    CONSTRAINT "FK_QUESTAO_AVALIACAO" FOREIGN KEY (ID_AVALIACAO)
        REFERENCES AVALIACAO(ID_AVALIACAO) ON DELETE CASCADE
);


-- Tabela de Respostas
CREATE TABLE RESPOSTA (
    ID_RESPOSTA INT NOT NULL,
    TEXTO_RESPOSTA TEXT,
    NOTA_OBTIDA NUMERIC(5, 2) CHECK (NOTA_OBTIDA >= 0),
    CONSTRAINT "PK_RESPOSTA" PRIMARY KEY (ID_RESPOSTA)
);


-- Tabela de Matrícula (relacionamento N:M entre Aluno e Disciplina)
CREATE TABLE MATRICULA (
    NUM_MATRICULA INT NOT NULL,
    ID_DISCIPLINA INT NOT NULL,
    CONSTRAINT "PK_MATRICULA" PRIMARY KEY (NUM_MATRICULA, ID_DISCIPLINA),
    CONSTRAINT "FK_MATRICULA_ALUNO" FOREIGN KEY (NUM_MATRICULA)
        REFERENCES ALUNO(NUM_MATRICULA) ON DELETE CASCADE,
    CONSTRAINT "FK_MATRICULA_DISCIPLINA" FOREIGN KEY (ID_DISCIPLINA)
        REFERENCES DISCIPLINA(ID_DISCIPLINA) ON DELETE CASCADE
);

-- Tabela Avaliacao_Questao (relacionamento N:M entre Avaliacao e Questao)
CREATE TABLE Avaliacao_Questao (
    ID_AVALIACAO INT NOT NULL,
    ID_QUESTAO INT NOT NULL,
    ID_PROFESSOR INT, -- Professor que elaborou/adicionou a questão na avaliação
    valor_total NUMERIC(5, 2) CHECK (valor_total >= 0),
    PRIMARY KEY (ID_AVALIACAO, ID_QUESTAO, ID_PROFESSOR),
    FOREIGN KEY (ID_AVALIACAO) REFERENCES Avaliacao(ID_AVALIACAO) ON DELETE CASCADE,
    FOREIGN KEY (ID_QUESTAO) REFERENCES Questao(ID_QUESTAO) ON DELETE CASCADE,
    FOREIGN KEY (ID_PROFESSOR) REFERENCES Professor(ID_PROFESSOR) ON DELETE SET NULL
);


-- Tabela de Submissão de Respostas
CREATE TABLE SUBMETE (
    NUM_MATRICULA INT NOT NULL,
    ID_RESPOSTA INT NOT NULL,
    CONSTRAINT "PK_SUBMETE" PRIMARY KEY (NUM_MATRICULA, ID_RESPOSTA),
    CONSTRAINT "UQ_SUBMETE_RESPOSTA" UNIQUE (ID_RESPOSTA),
    CONSTRAINT "FK_SUBMETE_ALUNO" FOREIGN KEY (NUM_MATRICULA)
        REFERENCES ALUNO(NUM_MATRICULA) ON DELETE CASCADE,
    CONSTRAINT "FK_SUBMETE_RESPOSTA" FOREIGN KEY (ID_RESPOSTA)
        REFERENCES RESPOSTA(ID_RESPOSTA) ON DELETE CASCADE
);

